#!/bin/sh


jsonify()
{
	echo -n '['
	sed -e '$!s/^/"/; $!s/$/",/; $s/^/"/; $s/$/"/;' | tr -d '\n'
	echo ']'
}

set -e
set -v

aspell -l cs dump master | grep '^[[:lower:]].*/[ZHSQMPUL]' | sed 's_/.*$__;' | jsonify > csNouns.json
